// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHJhKAQaU5NJS9uqkSdEOIUZvQ0H_0jP8',
    appId: '1:693831024087:web:fa0447ab5fe1efcda41f92',
    messagingSenderId: '693831024087',
    projectId: 'controlaccesoqr-341df',
    authDomain: 'controlaccesoqr-341df.firebaseapp.com',
    databaseURL: 'https://controlaccesoqr-341df-default-rtdb.firebaseio.com',
    storageBucket: 'controlaccesoqr-341df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwrw5lKR5UEnYoeiuTve5wRT0Vz74QK3o',
    appId: '1:693831024087:android:8353d5d814558026a41f92',
    messagingSenderId: '693831024087',
    projectId: 'controlaccesoqr-341df',
    databaseURL: 'https://controlaccesoqr-341df-default-rtdb.firebaseio.com',
    storageBucket: 'controlaccesoqr-341df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoefI6BaChPs8ekOlZ8vJS_DzMVT2dDF8',
    appId: '1:693831024087:ios:c7d0bd7786d18878a41f92',
    messagingSenderId: '693831024087',
    projectId: 'controlaccesoqr-341df',
    databaseURL: 'https://controlaccesoqr-341df-default-rtdb.firebaseio.com',
    storageBucket: 'controlaccesoqr-341df.firebasestorage.app',
    iosBundleId: 'com.example.scannerCarnetizacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoefI6BaChPs8ekOlZ8vJS_DzMVT2dDF8',
    appId: '1:693831024087:ios:c7d0bd7786d18878a41f92',
    messagingSenderId: '693831024087',
    projectId: 'controlaccesoqr-341df',
    databaseURL: 'https://controlaccesoqr-341df-default-rtdb.firebaseio.com',
    storageBucket: 'controlaccesoqr-341df.firebasestorage.app',
    iosBundleId: 'com.example.scannerCarnetizacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHJhKAQaU5NJS9uqkSdEOIUZvQ0H_0jP8',
    appId: '1:693831024087:web:1c3d205e0a2c8f66a41f92',
    messagingSenderId: '693831024087',
    projectId: 'controlaccesoqr-341df',
    authDomain: 'controlaccesoqr-341df.firebaseapp.com',
    databaseURL: 'https://controlaccesoqr-341df-default-rtdb.firebaseio.com',
    storageBucket: 'controlaccesoqr-341df.firebasestorage.app',
  );
}
