// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsu_Bi5Wd-AGFtP9A854ROTAs13_iPFlU',
    appId: '1:651690558061:web:029d17c6743b729e50f564',
    messagingSenderId: '651690558061',
    projectId: 'credenciales-f2be2',
    authDomain: 'credenciales-f2be2.firebaseapp.com',
    storageBucket: 'credenciales-f2be2.firebasestorage.app',
    databaseURL: 'https://credenciales-f2be2-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa14iX7WP9VzYyhqURy8HC2r2D_kTATyE',
    appId: '1:651690558061:android:3526ac8ccaf6788050f564',
    messagingSenderId: '651690558061',
    projectId: 'credenciales-f2be2',
    storageBucket: 'credenciales-f2be2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0bYYmZZ0Fhs0komRlTgQ7wy-An4gReK0',
    appId: '1:651690558061:ios:874ee9f96985056450f564',
    messagingSenderId: '651690558061',
    projectId: 'credenciales-f2be2',
    storageBucket: 'credenciales-f2be2.firebasestorage.app',
    iosClientId:
        '651690558061-c0ccq0h2hkbt0h2a6read2o3edavsubo.apps.googleusercontent.com',
    iosBundleId: 'com.example.scannerCarnetizacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0bYYmZZ0Fhs0komRlTgQ7wy-An4gReK0',
    appId: '1:651690558061:ios:874ee9f96985056450f564',
    messagingSenderId: '651690558061',
    projectId: 'credenciales-f2be2',
    storageBucket: 'credenciales-f2be2.firebasestorage.app',
    iosClientId:
        '651690558061-c0ccq0h2hkbt0h2a6read2o3edavsubo.apps.googleusercontent.com',
    iosBundleId: 'com.example.scannerCarnetizacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsu_Bi5Wd-AGFtP9A854ROTAs13_iPFlU',
    appId: '1:651690558061:web:a054e46950fb7eab50f564',
    messagingSenderId: '651690558061',
    projectId: 'credenciales-f2be2',
    authDomain: 'credenciales-f2be2.firebaseapp.com',
    storageBucket: 'credenciales-f2be2.firebasestorage.app',
  );
}
